<?php
namespace Techvoot\EIP\Rules;

class RuleRegistry
{
    /**
     * The single source of truth for all EIP rules.
     * Contains category, severity, risk weight, and maximum penalty per rule type.
     */
    public static function getRules(): array
    {
        return [
            // --- Sprint 3 New Rules ---
            'potential_circular_dependency' => [
                'title' => 'Potential Circular Dependency',
                'category' => 'architecture',
                'severity' => 'high',
                'risk' => 8,
                'max_penalty' => 24,
                'rule_type' => 'architectural',
                'confidence' => 'low',
                'classification' => 'manual_review_required',
                'note' => 'This finding is based on static analysis patterns and may vary depending on project architecture.',
                'version' => '1.0',
            ],
            'duplicate_helper_function' => [
                'title' => 'Duplicate Helper Function',
                'category' => 'quality',
                'severity' => 'warning',
                'risk' => 3,
                'max_penalty' => 10,
                'rule_type' => 'deterministic',
                'confidence' => 'high',
                'classification' => 'verified',
                'note' => '',
                'version' => '1.0',
            ],

            'job_payload_too_large' => [
                'title' => 'Job Payload May Be Too Large',
                'category' => 'performance',
                'severity' => 'warning',
                'risk' => 4,
                'max_penalty' => 12,
                'rule_type' => 'architectural',
                'confidence' => 'low',
                'classification' => 'manual_review_required',
                'note' => 'Large payloads in queued jobs can impact queue performance. Review if payload size is necessary.',
                'version' => '1.0',
            ],

            // --- Sprint 2 New Rules ---
            'service_dependency_overload' => [
                'title' => 'Service Has High Dependency Count',
                'category' => 'architecture',
                'severity' => 'warning',
                'risk' => 4,
                'max_penalty' => 12,
                'rule_type' => 'architectural',
                'confidence' => 'low',
                'classification' => 'manual_review_required',
                'note' => 'This finding is based on threshold configurations and architectural guidelines.',
                'version' => '1.0',
            ],
            'controller_dependency_overload' => [
                'title' => 'Controller Has High Dependency Count',
                'category' => 'architecture',
                'severity' => 'warning',
                'risk' => 4,
                'max_penalty' => 12,
                'rule_type' => 'architectural',
                'confidence' => 'low',
                'classification' => 'manual_review_required',
                'note' => 'This finding is based on threshold configurations and architectural guidelines.',
                'version' => '1.0',
            ],
            'missing_relationship_return_type' => [
                'title' => 'Missing Relationship Return Type',
                'category' => 'quality',
                'severity' => 'info',
                'risk' => 1,
                'max_penalty' => 5,
                'rule_type' => 'deterministic',
                'confidence' => 'high',
                'classification' => 'verified',
                'note' => '',
                'version' => '1.0',
            ],
            'missing_database_index' => [
                'title' => 'Missing Database Index',
                'category' => 'performance',
                'severity' => 'warning',
                'risk' => 4,
                'max_penalty' => 12,
                'rule_type' => 'deterministic',
                'confidence' => 'high',
                'classification' => 'verified',
                'note' => '',
                'version' => '1.0',
            ],
            'heavy_service_provider_boot' => [
                'title' => 'Heavy Service Provider Boot',
                'category' => 'performance',
                'severity' => 'warning',
                'risk' => 4,
                'max_penalty' => 12,
                'rule_type' => 'architectural',
                'confidence' => 'low',
                'classification' => 'manual_review_required',
                'note' => 'Expensive operations in ServiceProvider boot methods can slow down application startup.',
                'version' => '1.0',
            ],

            // --- Sprint 1 New Rules ---
            'missing_strict_types' => [
                'title' => 'Missing Strict Types Declaration',
                'category' => 'quality',
                'severity' => 'info',
                'risk' => 1,
                'max_penalty' => 10,
                'rule_type' => 'deterministic',
                'confidence' => 'high',
                'classification' => 'verified',
                'note' => '',
                'version' => '1.0',
            ],
            'query_in_controller' => [
                'title' => 'Query Executed In Controller',
                'category' => 'architecture',
                'severity' => 'warning',
                'risk' => 5,
                'max_penalty' => 20,
                'rule_type' => 'heuristic',
                'confidence' => 'medium',
                'classification' => 'manual_review_required',
                'note' => 'Based on heuristic detection. May vary depending on chosen architecture pattern.',
                'version' => '1.0',
            ],
            'missing_authorization_check' => [
                'title' => 'Potential Missing Authorization Check',
                'category' => 'security',
                'severity' => 'high',
                'risk' => 8,
                'max_penalty' => 24,
                'rule_type' => 'heuristic',
                'confidence' => 'medium',
                'classification' => 'manual_review_required',
                'note' => 'This finding is based on static analysis patterns and may vary depending on project architecture.',
                'version' => '1.0',
            ],
            'unguarded_model' => [
                'title' => 'Unguarded Model',
                'category' => 'security',
                'severity' => 'high',
                'risk' => 7,
                'max_penalty' => 21,
                'rule_type' => 'deterministic',
                'confidence' => 'high',
                'classification' => 'verified',
                'note' => '',
                'version' => '1.0',
            ],
            'migration_missing_rollback' => [
                'title' => 'Migration Missing Rollback Implementation',
                'category' => 'architecture',
                'severity' => 'high',
                'risk' => 5,
                'max_penalty' => 15,
                'rule_type' => 'deterministic',
                'confidence' => 'high',
                'classification' => 'verified',
                'note' => '',
                'version' => '1.0',
            ],
            'request_missing_authorization' => [
                'title' => 'Request May Lack Authorization',
                'category' => 'security',
                'severity' => 'high',
                'risk' => 6,
                'max_penalty' => 18,
                'rule_type' => 'heuristic',
                'confidence' => 'medium',
                'classification' => 'manual_review_required',
                'note' => 'FormRequest authorization may be handled elsewhere.',
                'version' => '1.0',
            ],
            'empty_validation_rules' => [
                'title' => 'Empty Validation Rules',
                'category' => 'security',
                'severity' => 'high',
                'risk' => 6,
                'max_penalty' => 18,
                'rule_type' => 'deterministic',
                'confidence' => 'high',
                'classification' => 'verified',
                'note' => '',
                'version' => '1.0',
            ],

            // --- Existing Rules ---
            'fat_controller' => [
                'title' => 'Fat Controller',
                'category' => 'architecture',
                'severity' => 'warning',
                'risk' => 4,
                'max_penalty' => 15,
                'rule_type' => 'architectural',
                'confidence' => 'low',
                'classification' => 'manual_review_required',
                'note' => 'Depends on line thresholds. May be acceptable in certain architectures.',
                'version' => '1.0',
            ],
            'long_method' => [
                'title' => 'Long Method Detected',
                'category' => 'architecture',
                'severity' => 'warning',
                'risk' => 3,
                'max_penalty' => 15,
                'rule_type' => 'architectural',
                'confidence' => 'low',
                'classification' => 'manual_review_required',
                'note' => 'Based on method line count thresholds.',
                'version' => '1.0',
            ],
            'missing_form_request' => [
                'title' => 'Missing Form Request Validation',
                'category' => 'security',
                'severity' => 'warning',
                'risk' => 3,
                'max_penalty' => 15,
                'rule_type' => 'heuristic',
                'confidence' => 'medium',
                'classification' => 'manual_review_required',
                'note' => 'Validation may be handled inline in the controller or service layer.',
                'version' => '1.0',
            ],
            'god_class_service' => [
                'title' => 'God Class Service',
                'category' => 'architecture',
                'severity' => 'warning',
                'risk' => 5,
                'max_penalty' => 20,
                'rule_type' => 'architectural',
                'confidence' => 'low',
                'classification' => 'manual_review_required',
                'note' => 'Services handling too many responsibilities should be refactored.',
                'version' => '1.0',
            ],
            'potential_sql_injection' => [
                'title' => 'Potential SQL Injection',
                'category' => 'security',
                'severity' => 'critical',
                'risk' => 10,
                'max_penalty' => 30,
                'rule_type' => 'deterministic',
                'confidence' => 'high',
                'classification' => 'verified',
                'note' => '',
                'version' => '1.0',
            ],
            'potential_n_plus_one' => [
                'title' => 'Potential N+1 Query',
                'category' => 'performance',
                'severity' => 'high',
                'risk' => 6,
                'max_penalty' => 24,
                'rule_type' => 'heuristic',
                'confidence' => 'medium',
                'classification' => 'manual_review_required',
                'note' => 'Static analysis heuristic. Verification via execution might be needed.',
                'version' => '1.0',
            ],
            'closure_route_detected' => [
                'title' => 'Closure Route Detected',
                'category' => 'quality',
                'severity' => 'warning',
                'risk' => 2,
                'max_penalty' => 10,
                'rule_type' => 'deterministic',
                'confidence' => 'high',
                'classification' => 'verified',
                'note' => '',
                'version' => '1.0',
            ],
            'env_helper_outside_config' => [
                'title' => 'Env Helper Used Outside Config',
                'category' => 'security',
                'severity' => 'warning',
                'risk' => 3,
                'max_penalty' => 15,
                'rule_type' => 'deterministic',
                'confidence' => 'high',
                'classification' => 'verified',
                'note' => '',
                'version' => '1.0',
            ],
            'event_contains_handler' => [
                'title' => 'Event Contains Handler Logic',
                'category' => 'architecture',
                'severity' => 'warning',
                'risk' => 3,
                'max_penalty' => 15,
                'rule_type' => 'architectural',
                'confidence' => 'low',
                'classification' => 'manual_review_required',
                'note' => 'Events should ideally just be DTOs without handler logic.',
                'version' => '1.0',
            ],
            'missing_transaction' => [
                'title' => 'Potential Missing Transaction',
                'category' => 'architecture',
                'severity' => 'warning',
                'risk' => 4,
                'max_penalty' => 16,
                'rule_type' => 'heuristic',
                'confidence' => 'medium',
                'classification' => 'manual_review_required',
                'note' => 'Multiple write operations detected without a database transaction block.',
                'version' => '1.0',
            ],
            'too_many_dependencies' => [
                'title' => 'Class Has Too Many Dependencies',
                'category' => 'architecture',
                'severity' => 'warning',
                'risk' => 4,
                'max_penalty' => 16,
                'rule_type' => 'architectural',
                'confidence' => 'low',
                'classification' => 'manual_review_required',
                'note' => 'Class may violate the Single Responsibility Principle.',
                'version' => '1.0',
            ],
            'synchronous_job_dispatch' => [
                'title' => 'Synchronous Job Dispatch',
                'category' => 'performance',
                'severity' => 'warning',
                'risk' => 4,
                'max_penalty' => 16,
                'rule_type' => 'architectural',
                'confidence' => 'low',
                'classification' => 'manual_review_required',
                'note' => 'Dispatching jobs synchronously defeats the purpose of the queue.',
                'version' => '1.0',
            ],
            'mass_assignment_vulnerability' => [
                'title' => 'Mass Assignment Vulnerability',
                'category' => 'security',
                'severity' => 'high',
                'risk' => 7,
                'max_penalty' => 21,
                'rule_type' => 'deterministic',
                'confidence' => 'high',
                'classification' => 'verified',
                'note' => '',
                'version' => '1.0',
            ],
        ];
    }

    public static function getRule(string $type): ?array
    {
        return self::getRules()[$type] ?? null;
    }
}
